# Source: https://docs.astral.sh/uv/guides/integration/gitlab/#using-uv-pip
image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim

stages:
  - test

# the .uv-cache is a global cache hashed by package contents...
# we want to persist this cache between CI runs so that uv can rebuild the venv quickly.
variables:
  UV_CACHE_DIR: .uv-cache

cache:
  # unique cache for each branch; same branch can reuse dependencies.
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .uv-cache/

test:
  stage: test
  script:

    - uv run pytest --junitxml=report.xml

  artifacts:
      when: always
      paths:
        - report.xml
      reports:
        junit: report.xml